Add missing 'always' value support to periodic every n-days parameters
voxpupuli/puppet-unattended_upgrades pull request #206
Opened 2021-12-01 13:52 UTC by Hufschmidt

#### Pull Request (PR) description

This does not seem to be documented in the default /etc/apt.conf.d/10periodic config,
but according to the implementation of `/usr/lib/apt/apt.systemd.daily` (which is called by `apt-daily-upgrade.service`)
some values also support 'always' in addition to positive integer value.

#### This Pull Request (PR) fixes the following issues

This change allows 'always' to be used for the following settings that support it and are managed by this module
* APT::Periodic::Update-Package-Lists
* APT::Periodic::Download-Upgradeable-Packages
* APT::Periodic::Unattended-Upgrade
* APT::Periodic::AutocleanInterval

Without this it is not possible to let the apt-daily.timer and apt-daily-upgrade.timer multiple times a day
since `/usr/lib/apt/apt.systemd.daily` what check its last timestamp against the value of the above settings
and abort.

2021-12-01 19:39 UTC, kenyon reviewed
Thanks for the pull request. Would be great if we could also have tests for these new values.

2021-12-02 09:23 UTC, bastelfreak approved these changes

2021-12-02 16:43 UTC, kenyon requested changes
Thanks for the tests! I should have noticed this before, but we should probably update the README to mention that `always` is an option for the `update` and `upgrade` parameters.

2021-12-03 09:17 UTC, Hufschmidt commented
Good idea, added information to README.md.

2021-12-03 19:38 UTC, kenyon approved these changes

2021-12-03 19:38 UTC, merged